name: Resualbe Deploy
on: workflow_call                     
jobs:
  deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy
          run: |
            ls ${{ github.workspace }}
            echo "Deploying..."